### When Was the Best Era of Video Games?

In [5]:
-- best_selling_games
SELECT *
FROM game_sales
ORDER BY games_sold DESC
LIMIT 10;

                                        name platform  ... games_sold  year
0                         Wii Sports for Wii      Wii  ...      82.90  2006
1                  Super Mario Bros. for NES      NES  ...      40.24  1985
2    Counter-Strike: Global Offensive for PC       PC  ...      40.00  2012
3                     Mario Kart Wii for Wii      Wii  ...      37.32  2008
4       PLAYERUNKNOWN'S BATTLEGROUNDS for PC       PC  ...      36.60  2017
5                           Minecraft for PC       PC  ...      33.15  2010
6                  Wii Sports Resort for Wii      Wii  ...      33.13  2009
7  Pokemon Red / Green / Blue Version for GB       GB  ...      31.38  1998
8               New Super Mario Bros. for DS       DS  ...      30.80  2006
9          New Super Mario Bros. Wii for Wii      Wii  ...      30.30  2009

[10 rows x 6 columns]

In [6]:
-- critics_top_ten_by_years
SELECT g.year, COUNT(g.name) AS num_games, ROUND(AVG(r.critic_score),2) AS avg_critic_score
FROM game_sales g
INNER JOIN reviews r
ON g.name = r.name
GROUP BY g.year
HAVING COUNT(g.name) >= 4
ORDER BY avg_critic_score DESC
LIMIT 10;

   year  num_games  avg_critic_score
0  1998         10              9.32
1  2004         11              9.03
2  2002          9              8.99
3  1999         11              8.93
4  2001         13              8.82
5  2011         26              8.76
6  2016         13              8.67
7  2013         18              8.66
8  2008         20              8.63
9  2017         13              8.62

In [7]:
-- the_best_years
SELECT u.year, u.num_games, c.avg_critic_score, u.avg_user_score, c.avg_critic_score - u.avg_user_score AS diff
FROM critics_avg_year_rating c
INNER JOIN users_avg_year_rating u
ON c.year = u.year
WHERE c.avg_critic_score > 9 OR u.avg_user_score > 9
ORDER BY year ASC

   year  num_games  avg_critic_score  avg_user_score  diff
0  1997          8              7.93            9.50 -1.57
1  1998         10              9.32            9.40 -0.08
2  2004         11              9.03            8.55  0.48
3  2008         20              8.63            9.03 -0.40
4  2009         20              8.55            9.18 -0.63
5  2010         23              8.41            9.24 -0.83